/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'IdentifyMsg'
 * message type.
 */

public class IdentifyMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 19;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 40;

    /** Create a new IdentifyMsg of size 19. */
    public IdentifyMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new IdentifyMsg of the given data_length. */
    public IdentifyMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new IdentifyMsg with the given data_length
     * and base offset.
     */
    public IdentifyMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new IdentifyMsg using the given byte array
     * as backing store.
     */
    public IdentifyMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new IdentifyMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public IdentifyMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new IdentifyMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public IdentifyMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new IdentifyMsg embedded in the given message
     * at the given base offset.
     */
    public IdentifyMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new IdentifyMsg embedded in the given message
     * at the given base offset and length.
     */
    public IdentifyMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <IdentifyMsg> \n";
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct IdentifyMsg 19 40
=0x"+Long.toHexString(get_nx_struct IdentifyMsg 19 40
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct IdentifyMsg 19 40

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   replyOn Nnx_uint8_t 32 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is signed (false).
     */
    public static boolean isSigned_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct IdentifyMsg 19 40
' is an array (false).
     */
    public static boolean isArray_nx_struct IdentifyMsg 19 40
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offset_nx_struct IdentifyMsg 19 40
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int offsetBits_nx_struct IdentifyMsg 19 40
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public  get_nx_struct IdentifyMsg 19 40
() {
        return ()get(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
);
    }

    /**
     * Set the value of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public void set_nx_struct IdentifyMsg 19 40
( value) {
        set(offsetBits_nx_struct IdentifyMsg 19 40
(),   replyOn Nnx_uint8_t 32 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int size_nx_struct IdentifyMsg 19 40
() {
        return (  replyOn Nnx_uint8_t 32 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct IdentifyMsg 19 40
'
     */
    public static int sizeBits_nx_struct IdentifyMsg 19 40
() {
        return   replyOn Nnx_uint8_t 32 8
;
    }

}
