/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'PingMsg'
 * message type.
 */

public class PingMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 5;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 11;

    /** Create a new PingMsg of size 5. */
    public PingMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new PingMsg of the given data_length. */
    public PingMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PingMsg with the given data_length
     * and base offset.
     */
    public PingMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PingMsg using the given byte array
     * as backing store.
     */
    public PingMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PingMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public PingMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PingMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public PingMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PingMsg embedded in the given message
     * at the given base offset.
     */
    public PingMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PingMsg embedded in the given message
     * at the given base offset and length.
     */
    public PingMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <PingMsg> \n";
      try {
        s += "  [nx_struct PingMsg 5 11
=0x"+Long.toHexString(get_nx_struct PingMsg 5 11
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct PingMsg 5 11
=0x"+Long.toHexString(get_nx_struct PingMsg 5 11
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct PingMsg 5 11
=0x"+Long.toHexString(get_nx_struct PingMsg 5 11
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nx_struct PingMsg 5 11
=0x"+Long.toHexString(get_nx_struct PingMsg 5 11
())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct PingMsg 5 11

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   txpower Nnx_uint8_t 24 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct PingMsg 5 11
' is signed (false).
     */
    public static boolean isSigned_nx_struct PingMsg 5 11
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct PingMsg 5 11
' is an array (false).
     */
    public static boolean isArray_nx_struct PingMsg 5 11
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct PingMsg 5 11
'
     */
    public static int offset_nx_struct PingMsg 5 11
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct PingMsg 5 11
'
     */
    public static int offsetBits_nx_struct PingMsg 5 11
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct PingMsg 5 11
'
     */
    public  get_nx_struct PingMsg 5 11
() {
        return ()get(offsetBits_nx_struct PingMsg 5 11
(),   txpower Nnx_uint8_t 24 8
);
    }

    /**
     * Set the value of the field 'nx_struct PingMsg 5 11
'
     */
    public void set_nx_struct PingMsg 5 11
( value) {
        set(offsetBits_nx_struct PingMsg 5 11
(),   txpower Nnx_uint8_t 24 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct PingMsg 5 11
'
     */
    public static int size_nx_struct PingMsg 5 11
() {
        return (  txpower Nnx_uint8_t 24 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct PingMsg 5 11
'
     */
    public static int sizeBits_nx_struct PingMsg 5 11
() {
        return   txpower Nnx_uint8_t 24 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct PingMsg 5 11

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   txpower Nnx_uint8_t 24 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct PingMsg 5 11
' is signed (false).
     */
    public static boolean isSigned_nx_struct PingMsg 5 11
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct PingMsg 5 11
' is an array (false).
     */
    public static boolean isArray_nx_struct PingMsg 5 11
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct PingMsg 5 11
'
     */
    public static int offset_nx_struct PingMsg 5 11
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct PingMsg 5 11
'
     */
    public static int offsetBits_nx_struct PingMsg 5 11
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct PingMsg 5 11
'
     */
    public  get_nx_struct PingMsg 5 11
() {
        return ()get(offsetBits_nx_struct PingMsg 5 11
(),   txpower Nnx_uint8_t 24 8
);
    }

    /**
     * Set the value of the field 'nx_struct PingMsg 5 11
'
     */
    public void set_nx_struct PingMsg 5 11
( value) {
        set(offsetBits_nx_struct PingMsg 5 11
(),   txpower Nnx_uint8_t 24 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct PingMsg 5 11
'
     */
    public static int size_nx_struct PingMsg 5 11
() {
        return (  txpower Nnx_uint8_t 24 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct PingMsg 5 11
'
     */
    public static int sizeBits_nx_struct PingMsg 5 11
() {
        return   txpower Nnx_uint8_t 24 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct PingMsg 5 11

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   txpower Nnx_uint8_t 24 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct PingMsg 5 11
' is signed (false).
     */
    public static boolean isSigned_nx_struct PingMsg 5 11
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct PingMsg 5 11
' is an array (false).
     */
    public static boolean isArray_nx_struct PingMsg 5 11
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct PingMsg 5 11
'
     */
    public static int offset_nx_struct PingMsg 5 11
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct PingMsg 5 11
'
     */
    public static int offsetBits_nx_struct PingMsg 5 11
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct PingMsg 5 11
'
     */
    public  get_nx_struct PingMsg 5 11
() {
        return ()get(offsetBits_nx_struct PingMsg 5 11
(),   txpower Nnx_uint8_t 24 8
);
    }

    /**
     * Set the value of the field 'nx_struct PingMsg 5 11
'
     */
    public void set_nx_struct PingMsg 5 11
( value) {
        set(offsetBits_nx_struct PingMsg 5 11
(),   txpower Nnx_uint8_t 24 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct PingMsg 5 11
'
     */
    public static int size_nx_struct PingMsg 5 11
() {
        return (  txpower Nnx_uint8_t 24 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct PingMsg 5 11
'
     */
    public static int sizeBits_nx_struct PingMsg 5 11
() {
        return   txpower Nnx_uint8_t 24 8
;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nx_struct PingMsg 5 11

    //   Field type: 
    //   Offset (bits): 0
    //   Size (bits):   txpower Nnx_uint8_t 24 8

    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nx_struct PingMsg 5 11
' is signed (false).
     */
    public static boolean isSigned_nx_struct PingMsg 5 11
() {
        return false;
    }

    /**
     * Return whether the field 'nx_struct PingMsg 5 11
' is an array (false).
     */
    public static boolean isArray_nx_struct PingMsg 5 11
() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nx_struct PingMsg 5 11
'
     */
    public static int offset_nx_struct PingMsg 5 11
() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nx_struct PingMsg 5 11
'
     */
    public static int offsetBits_nx_struct PingMsg 5 11
() {
        return 0;
    }

    /**
     * Return the value (as a ) of the field 'nx_struct PingMsg 5 11
'
     */
    public  get_nx_struct PingMsg 5 11
() {
        return ()get(offsetBits_nx_struct PingMsg 5 11
(),   txpower Nnx_uint8_t 24 8
);
    }

    /**
     * Set the value of the field 'nx_struct PingMsg 5 11
'
     */
    public void set_nx_struct PingMsg 5 11
( value) {
        set(offsetBits_nx_struct PingMsg 5 11
(),   txpower Nnx_uint8_t 24 8
, value);
    }

    /**
     * Return the size, in bytes, of the field 'nx_struct PingMsg 5 11
'
     */
    public static int size_nx_struct PingMsg 5 11
() {
        return (  txpower Nnx_uint8_t 24 8
 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nx_struct PingMsg 5 11
'
     */
    public static int sizeBits_nx_struct PingMsg 5 11
() {
        return   txpower Nnx_uint8_t 24 8
;
    }

}
