#COMPONENT=RssiBaseAppC

INCLUDES= -I..               		\
          -I../Reset		 		\
          -I$(TOSDIR)/lib/net 		\
          -I$(TOSDIR)/lib/net/le	\
          -I$(TOSDIR)/lib/net/ctp	

CFLAGS += $(INCLUDES)

include $(MAKERULES)
